2014-02-27 13:56:41,258 [Thread-4:-1238369472] [django.request:226] [ERROR]- Internal Server Error: /xls201402/
Traceback (most recent call last):
  File "/home/robin/Env/xls/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Env/xls/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/robin/Env/xls/project/xls/views.py", line 77, in upload_xls
    return _upload_xls(request)
  File "/home/robin/Env/xls/project/xls/views.py", line 57, in _upload_xls
    ret,file_name, file_url = handle_uploaded_file(file1, "uploads/xls")
ValueError: need more than 2 values to unpack
2014-02-27 13:56:41,837 [Thread-5:-1238369472] [django.request:145] [WARNING]- Not Found: /favicon.ico
2014-02-27 14:16:37,945 [Thread-5:-1238369472] [django.request:145] [WARNING]- Not Found: /media/uploads/xls/out.csv
2014-03-13 13:35:28,423 [Thread-1:-1238369472] [django.request:145] [WARNING]- Not Found: /
2014-03-13 13:35:28,566 [Thread-3:-1238369472] [django.request:145] [WARNING]- Not Found: /favicon.ico
2014-03-13 13:35:28,593 [Thread-4:-1238369472] [django.request:145] [WARNING]- Not Found: /favicon.ico
